### PR TITLE
Dendy mode should not use same PAL mode

### PR DESCRIPTION
**Pull request by MCPE22**
**Dendy mode** is designed to play NTSC VRC6 Mapper, VRC7 Mapper, FDS Mapper, N163 Mapper, S5B Mapper Games in 50Hz without glitch / garbled graphics (Akumajou Densetsu VRC6, Lagrange Point VRC7 on PAL 50Hz NES Clone Dendy)

### CODE REVIEW

**Comment by rdanbrook** [comment]
@eugene-s-nesdev do you have any idea about this? I keep getting this issue posted and no real details, so maybe a Dendy expert can help me figure out what this guy is trying to say exactly.

**Comment by eugene-s-nesdev** [comment]
Hi, Rdanbrook. I'm confused too.
NestopiaUE already have correct dendy-timing working for all *.nes (all mappers, including VRC6/7 etc) and *.fds roms.
I tested lastest Windows port (1.50UE), maybe linux is broken? 
I will test it soon.
As i know, the only existing [core] issue is "region changing on the fly", mentioned here:
https://gitlab.com/jgemu/nestopia/-/issues/6

**Comment by eugene-s-nesdev** [comment]
I've just compiled lastest linux version, set dendy mode, and then opened some roms, all works perfectly correct in dendy mode:
timing
aku
gimmick

Global bug that i found - fds roms don't open in any (ntsc/pal/dendy) mode, give black screen.

**Comment by rdanbrook** [comment]
@eugene-s-nesdev thanks for doing this, you helped confirm that things are actually already in a working state.

I think the author of this PR must be using Windows, because the options are a little weird there for regions, and I think if you set the wrong combination then the behaviour might not be correct.

By the way, I did release newer Windows binaries at version 1.51.1: http://sourceforge.net/projects/nestopiaue/files/1.51/nestopia_1.51.1-win32.zip/download

**Pull request closed without merging**
