### PR TITLE
libretro: adjustable audio rate

### PR DESCRIPTION
**Pull request by creambits**
can use higher rates like 96000, 384000 (Sameboy) and have frontend down interpolate

### CODE REVIEW

**Comment by rdanbrook** [comment]
I'm not a big fan of littering the core with preprocessor directives specific to one port. I also don't see how this actually changes the libretro port, it just replaces a hardcoded value with a define that has the same value. In other words, I'm failing to see the point of this pull request.

**Comment by creambits** [comment]
The only real problem with the libretro port is this line: ```audio_batch_cb(audio_stereo_buffer, frames);```. Try it with higher audio rates of 96000, 384000 and the audio will crackle and distort and not sound correct. If we send data over to frontend in 1024 frames, sound is correct again.

Reference: https://github.com/0ldsk00l/nestopia/issues/303

Mesen would use a higher default libretro rate but given how slow it runs, it was kept at 48000. Sameboy uses 384000 and sounds clean. I would set it to 96000 or 384000 for Nestopia since it doesn't add much cpu overhead but not sure how it would affect mobile phones (when used with runahead latency).

After some more thought, I'll just scrap this PR and keep it for myself. 48000 is good enough to satisfy most people anyway.

**Comment by rdanbrook** [comment]
Honestly, there is very little difference anyway once you go past 96KHz. I have not looked at how resampling is done in Nestopia to be honest, but in my own emulator I decimate before resampling. There is likely going to be a point where you max out the amount of raw samples you can read out of the emulator core, and at that point you can't improve the audio quality any more, unless you really want to downsample from ~1.79MHz by doing no decimation at all. I would be open to making this change, but currently have too much other stuff going on to take something of that magnitude on.

I do think it makes sense to get rid of any hardcoded values though, so maybe I will do that myself for the libretro port.

**Comment by creambits** [comment]
Nestopia 48K => 96K I can notice a change; less smidges, blurs, noise. Above that I honestly wouldn't care but frontend has a nice sinc filter to step it down as opposed to some other methods. So I just take advantage of it and close off any further gains from my mind, even though it's probably all mental.

**Pull request closed without merging**
