### PR TITLE
sound savestates

### PR DESCRIPTION
**Pull request by creambits**
reproduce 1:1 bitstream after loadstate

### CODE REVIEW

**Comment by rdanbrook** [comment]
Will look into this soon. Does it change the sizes of any existing variables, or add new variables that would impact compatibility?

**Comment by creambits** [comment]
Adds new variables. Old savestates load correctly. Also tried newer savestates on older nestopia builds and load correctly there also.

**Comment by rdanbrook** [comment]
Hmmm... What games did you try to load new savestates on old builds with? I just tested an MMC3 game and it simply resets if I load a savestate generated with your changes.

**Comment by rdanbrook** [comment]
Merged! I haven't found any problems testing a wide array of games. If there are any problems, surely other people will be able to find them post-merge :).

Thanks a lot for taking this on and making this change.

**Pull request merged**
