### PR TITLE
Notcurses support for console graphics

### PR DESCRIPTION
**Pull request by dankamongmen**
notcurses provides DirectColor RGB and other advanced
capabilities in character graphics mode. This adds
autotools support for an --enable-tui option (exclusive
viz --enable-gui). When compiled with TUI support,
-x/--text can be supplied on the CLI to use notcurses,
rendering directly to the spawning terminal.

A terminal geometry of at least 256x112 is necessary
for perfect fidelity, as is 24-bit color support.

2020-02-02-024256_1186x922_scrot

### CODE REVIEW

**Comment by dankamongmen** [comment]
https://www.youtube.com/watch?v=PHOHxqGkTUA shows this capability off.

I know this is probably not the kind of thing you're looking for in what appears to be maintenance-mode nestopia. It's freakin' awesome, though :). I can make any code changes you'd like to the PR, but I'd really like to get this in there -- let me know if there's anything you need me to do. Thanks!

**Comment by rdanbrook** [comment]
I really want to stay in maintenance mode. The problem is this is too cool to not merge. Give me some time to review before merging as internet access is unpredictable for me at the moment.

**Comment by dankamongmen** [comment]
> I really want to stay in maintenance mode. The problem is this is too cool to not merge. Give me some time to review before merging as internet access is unpredictable for me at the moment.

you make my heart sing <3 i'm happy to do whatever's necessary to get in. i notice that you're involved in libretro. i was hoping to use this as something of a jumping-off-point to get to libretro (I intend to make notcurses a full GL rendering target). so if you'd rather we do stuff there, i'm down.

**Comment by rdanbrook** [comment]
If you want to get notcurses into libretro, I'd advise doing a pull request to RetroArch with notcurses as a video driver. I'm sure the libretro team would be happy to have it.

**Comment by dankamongmen** [comment]
It's a more complex goal, but yeah, it's the aim. The other thing is that I'm not yet in Debian/Ubuntu with notcurses (only in Arch), so I figured libretro might reject it out of hand.

On your advice, I'm going to go ahead and see what I can do there. Definitely feel free to merge this if you'd like; it seems pretty self-contained, and the pickup would definitely help me in this initial period of trying to get pickup in distros. That's a purely political motivation, though, so likewise feel free to close this PR :D.

**Comment by dankamongmen** [comment]
> Date: Tue, 4 Feb 2020 22:29:07 -0500
From: Nick Black <dankamongmen@gmail.com>
To: libretro@gmail.com
Subject: looking to set up notcurses as a libretro video out

> Hello there!

> I'm the author of notcurses (https://github.com/dankamongmen/notcurses),
a new library for character-based graphics. Imagine ncurses and
ffmpeg had a baby -- that's notcurses. I offer up the same type
of 2d drawing primitives as ncurses, but also 24-bit RGB color,
transparencies, image/video support, multithreading sanity, and
direct BGR/RGB blitting.

> This weekend, I successfully plugged in notcurses as a rendering
backend for NEStopia 1.5:

>  https://www.youtube.com/watch?v=PHOHxqGkTUA

> I submitted the result as a PR for nestopia:

> https://github.com/0ldsk00l/nestopia/pull/328

> But NEStopia is in maintenance mode, having yielded way to
libretro. The maintainer, @rdanbrook, recommended that I go
directly to libretro. So here I am. I'd like very much to bring
in notcurses as a libretro target, and am happy to study the
project and do so myself. I assume it'll take about a week,
given that I have other obligations.

> Before I do so, however, I'd like to know whether this would be
considered for acceptance. notcurses is in the Arch AUR, but not
yet in Debian/Ubuntu (I make packages available for both at
https://dsscaw.com/apt.html). Obviously, it would be an optional
dependency/component, but would this work be rejected
out-of-hand?

> Thanks for your time! Hack on!

> --rigorously, nick

> --
nick black -=- https://www.nick-black.com
to make an apple pie from scratch,
you need first invent a universe.

**Comment by twinaphex** [comment]
Hi there,

I read the email and I want to say, I very much welcome this. 

I think you want to approach it from a different perspective, though. You would do this by implementing a video driver in RetroArch. You can add a HAVE_NOTCURSES define for it and it can be added to the qb configure scripts.

Also, maybe the existing libcaca driver can help you out in writing your own notcurses driver for RetroArch.

Anyway, we very much welcome new technologies, so the more the merrier.

**Comment by dankamongmen** [comment]
> Hi there,
> 
> I read the email and I want to say, I very much welcome this.
> 
> I think you want to approach it from a different perspective, though. You would do this by implementing a video driver in RetroArch. You can add a HAVE_NOTCURSES define for it and it can be added to the qb configure scripts.
> 
> Also, maybe the existing libcaca driver can help you out in writing your own notcurses driver for RetroArch.
> 
> Anyway, we very much welcome new technologies, so the more the merrier.

Outstanding. I was more worried that libretro, being an active project, would not want to admit a package which isn't yet in many distros. I confirmed with my sponsor that notcurses will be uploaded to Debian Unstable within a week, and if it passes ftpmaster review, it'll at least be there. It ought then fall into Ubuntu Focal naturally (I already have a Focal build distributed at https://dsscaw.com/apt.html, much like Debian Unstable).

Thanks so much for your support! I should have a libretro PR prepared by the end of this weekend, I'd think. How exciting! I'd love to be part of RetroArch!

**Comment by rdanbrook** [comment]
Decided not to merge due to new project goals. Don't take it personally, I still think what you did is cool.

**Comment by dankamongmen** [comment]
> Decided not to merge due to new project goals. Don't take it personally, I still think what you did is cool.

no problem at all man! thanks for considering it and pointing me towards RetroArch.

**Pull request closed without merging**
